
service:
  image: dockerrepo.eionet.europa.eu:5000/eionet/datalake:latest
  ports:
  - "4590:8080"
  labels:
    io.rancher.scheduler.affinity:host_label: publicip=178.239.183.132
  environment:
    CATALINA_OPTS: |
      -Dinitial.username=roug
      -Djava.security.egd=file:/dev/./urandom
      -Dcas.service=http://178.239.183.132:4590
      -Ddb.driver=org.mariadb.jdbc.Driver
      -Ddb.url=jdbc:mariadb://dbservice/datalake
      -Ddb.username=datalake
      -Ddb.password=yubetisaqe
      -Djava.io.tmpdir=/var/tmp
  links:
  - dbservice
  volumes:
  - /var/local/datalake/files:/var/tmp:z

dbservice:
  image: mariadb:10.1
  environment:
  - MYSQL_ROOT_PASSWORD=mayeceju
  - MYSQL_DATABASE=datalake
  - MYSQL_USER=datalake
  - MYSQL_PASSWORD=yubetisaqe
  command:
  - mysqld
  - --character-set-server=utf8
  - --collation-server=utf8_general_ci
  labels:
    io.rancher.sidekicks: dbdata
  volumes_from:
  - dbdata

#
# Use the storage pool
#
dbdata:
  image: tianon/true
  volumes:
  - /var/local/datalake/mysql:/var/lib/mysql:z
# - datalake_mysql:/var/lib/mysql:z
  labels:
    io.rancher.container.start_once: "true"

